transcript_source: seeking_alpha
price_source: yfinance
transcript_dir: "./transcript_data"
embedding_model: FinLang/finance-embeddings-investopedia
alpha_model: logistic
use_pca: true
pca_n_components: 0.95
holding_periods: [5]
prediction_target: direction
use_market_neutral: true
benchmark_ticker: SPY
labeling_strategy: quantile
train_test_split_date: "2023-01-01"
random_seed: 42
use_hyperparam_tuning: false
tuner_param_grid_path: "./configs/params.json"
tuner_scoring_metric: accuracy
output_dir: ./outputs
cache_dir: ./cache
log_level: DEBUG